import os
import json
from google.genai.types import HttpRetryOptions
from google.adk.models.google_llm import Gemini
from google.adk import Agent, Workflow, Context
from google.adk.tools import ToolContext
from google.adk.workflow import RetryConfig
from routing_service import RoutingService

# 1. Configuration & Service Setup
MODEL = Gemini(
    model="gemini-2.0-flash",
    retry_options=HttpRetryOptions(
        attempts=5,
        initial_delay=1.0,
        exp_base=2.0,
        http_status_codes=[429, 500, 503, 504]
    )
)

agent_retry_config = RetryConfig(
    max_attempts=5,
    initial_delay=2.0,
    max_delay=60.0,
    backoff_factor=2.0,
    jitter=1.0
)

CRIME_PATH = r"C:\Users\dell\OneDrive\Documents\JN\all syllabussss\discrete mathematics\semester 4\crime_dataset (1) (1).json"
METRO_PATH = r"C:\Users\dell\OneDrive\Documents\JN\all syllabussss\discrete mathematics\semester 4\Delhi metro.csv"
BOUNDARY_PATH = r"C:\Users\dell\OneDrive\Documents\JN\all syllabussss\discrete mathematics\semester 4\Delhi_Boundary.geojson"
POLICE_CSV_PATH = r"c:\Users\dell\OneDrive\Documents\JN\all syllabussss\discrete mathematics\semester 4\delhi_police_station_locs.csv"

routing_service = RoutingService(
    crime_path=CRIME_PATH,
    metro_path=METRO_PATH,
    boundary_path=BOUNDARY_PATH,
    police_csv_path=POLICE_CSV_PATH
)

# 2. Tool & MCP Setup
import sys
from google.adk.tools import McpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams
from mcp import StdioServerParameters

mcp_server_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "safegrid_mcp_server.py")

# Create separate Toolsets with filters to enforce agent-to-tool mapping
route_toolset = McpToolset(
    connection_params=StdioConnectionParams(
        server_params=StdioServerParameters(
            command=sys.executable,
            args=[mcp_server_path]
        ),
        timeout=30.0
    ),
    tool_filter=["get_safe_route"]
)

crime_toolset = McpToolset(
    connection_params=StdioConnectionParams(
        server_params=StdioServerParameters(
            command=sys.executable,
            args=[mcp_server_path]
        ),
        timeout=30.0
    ),
    tool_filter=["analyze_route_risk", "detect_hotspots"]
)

recommendation_toolset = McpToolset(
    connection_params=StdioConnectionParams(
        server_params=StdioServerParameters(
            command=sys.executable,
            args=[mcp_server_path]
        ),
        timeout=30.0
    ),
    tool_filter=["get_safety_recommendation"]
)

emergency_toolset = McpToolset(
    connection_params=StdioConnectionParams(
        server_params=StdioServerParameters(
            command=sys.executable,
            args=[mcp_server_path]
        ),
        timeout=30.0
    ),
    tool_filter=["nearest_police_station", "nearest_metro", "nearest_hospital", "find_police_on_route"]
)

# 3. Agent Declarations

route_agent = Agent(
    name="RouteAgent",
    model=MODEL,
    description="Handles geocoding and route planning.",
    instruction="""
    You are the Route Intelligence Agent. Your job is to plan the safest route between two places.
    1. Parse the input string which describes the query (e.g., 'Source: X, Destination: Y').
    2. Extract the source and destination names.
    3. Call the `get_safe_route` tool using these source and destination names.
    4. Save the output string returned by `get_safe_route` as a JSON string inside the 'route_info' key in state.
    5. Return exactly the JSON string generated by the `get_safe_route` tool.
    """,
    tools=[route_toolset],
    output_key="route_info",
    retry_config=agent_retry_config
)

crime_agent = Agent(
    name="CrimeAgent",
    model=MODEL,
    description="Analyzes crime risk levels for a route.",
    instruction="""
    You are the Crime Analysis Agent.
    1. Read 'route_info' from context state. It contains a JSON with 'route_cells'.
    2. Extract the list of 'route_cells'.
    3. Pass the cells JSON as a JSON string to `analyze_route_risk` to determine the risk percentage score and risk level (LOW/MEDIUM/HIGH).
    4. Pass the cells JSON as a JSON string to `detect_hotspots` to get a list of active crime hotspots.
    5. Output the result as a single JSON string containing:
       - risk_score: risk percentage (0-100)
       - risk_level: string (LOW, MEDIUM, HIGH)
       - hotspots: list of strings
       Weave the calculations from both tools into this single JSON output.
    """,
    tools=[crime_toolset],
    output_key="risk_info",
    retry_config=agent_retry_config
)

recommendation_agent = Agent(
    name="RecommendationAgent",
    model=MODEL,
    description="Generates final user-facing safety suggestions.",
    instruction="""
    You are the Recommendation Agent. Your job is to format the final user safety advice.
    1. Read 'route_info', 'risk_info', and 'emergency_output' from context state.
    2. Call `get_safety_recommendation` using the risk_score and risk_level from state.
    3. Generate a clean, user-friendly summary of the route path, safety recommendation, and nearby police stations in Markdown format.
    4. For example:
       ### Safety Assessment
       - **Route Summary**: Route found from [Source] to [Destination]. Distance: [Distance] km. ETA: [ETA] mins.
       - **Risk Level**: [Risk Level (e.g. HIGH)]
       - **Risk Score**: [Risk Score (e.g. 78%)]
       
       ### Nearby Police Stations Along Route
       [Format a bulleted list of unique police stations from 'emergency_output' JSON, showing distance in meters. If no police stations are present or the list is empty, state: 'No police stations found within 1km of the route.']
       
       ### Safety Advice & Recommendations
       - [List safety recommendations here]
    """,
    tools=[recommendation_toolset],
    output_key="final_recommendation",
    retry_config=agent_retry_config
)

emergency_agent = Agent(
    name="EmergencyAgent",
    model=MODEL,
    description="Finds nearby emergency services and police stations along a route.",
    instruction="""
    You are the Emergency Agent.
    1. Check if 'route_info' is present in the context state.
       - If 'route_info' is present, extract 'route_cells' from it (it contains a list of cells).
       - Call the `find_police_on_route` tool using these route cells.
       - Return exactly the JSON string returned by the `find_police_on_route` tool.
    2. If 'route_info' is NOT present in the context state, read the input query which describes the user's location (e.g. 'User Location: X').
       - Extract the location name or coordinates.
       - Use your internal geographical knowledge to estimate the latitude and longitude coordinates of that location.
       - Call `nearest_police_station`, `nearest_metro`, and `nearest_hospital` using the coordinates.
       - Generate a final response in Markdown format, listing the nearest services and 3 quick safety advice steps for an SOS situation.
    """,
    tools=[emergency_toolset],
    output_key="emergency_output",
    retry_config=agent_retry_config
)

# 4. Workflows Setup

def return_safety_output(ctx: Context) -> dict:
    try:
        route_info = json.loads(ctx.state.get("route_info", "{}"))
    except:
        route_info = {}
    try:
        risk_info = json.loads(ctx.state.get("risk_info", "{}"))
    except:
        risk_info = {}
    try:
        police_on_route = json.loads(ctx.state.get("emergency_output", "[]"))
        if not isinstance(police_on_route, list):
            police_on_route = []
    except:
        police_on_route = []
    
    return {
        "route_found": route_info.get("route_found", False),
        "distance_km": route_info.get("distance_km", 0.0),
        "eta_min": route_info.get("eta_min", 0),
        "route_cells": route_info.get("route_cells", []),
        "risk_score": risk_info.get("risk_score", 0),
        "risk_level": risk_info.get("risk_level", "UNKNOWN"),
        "hotspots": risk_info.get("hotspots", []),
        "police_on_route": police_on_route,
        "recommendation": ctx.state.get("final_recommendation", "")
    }

def return_emergency_output(ctx: Context) -> dict:
    return {
        "emergency_info": ctx.state.get("emergency_output", "No emergency services found.")
    }

safety_workflow = Workflow(
    name="SafetyWorkflow",
    edges=[
        ("START", route_agent),
        (route_agent, crime_agent),
        (crime_agent, emergency_agent),
        (emergency_agent, recommendation_agent),
        (recommendation_agent, return_safety_output)
    ]
)

emergency_workflow = Workflow(
    name="EmergencyWorkflow",
    edges=[
        ("START", emergency_agent),
        (emergency_agent, return_emergency_output)
    ]
)
